[tool.poetry]
name = "unittest-proj"
version = "0.1.0"
description = ""
authors = ["Sveta Lalayan <lalayan-svetlana@list.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
coverage = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
